name: Renovate Config Linting
on:
  pull_request:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 🧼 lint renovate config # Validates changes to renovate.json config file
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.1.0
        with:
          config_file_path: 'renovate.json'
